# Generated by Django 6.0.2 on 2026-02-16 00:00

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_listing_plans(apps, schema_editor):
    ListingPlan = apps.get_model("payments", "ListingPlan")
    ListingPlan.objects.update_or_create(
        code="BASIC",
        defaults={
            "name": "Basic Listing",
            "price": "10.00",
            "duration_days": 30,
            "is_featured": False,
            "is_active": True,
        },
    )
    ListingPlan.objects.update_or_create(
        code="FEATURED",
        defaults={
            "name": "Featured Listing",
            "price": "25.00",
            "duration_days": 30,
            "is_featured": True,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("properties", "0004_property_verification_and_publish_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(choices=[("BASIC", "Basic"), ("FEATURED", "Featured")], max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration_days", models.PositiveIntegerField(default=30)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["price"]},
        ),
        migrations.CreateModel(
            name="ListingPaymentIntent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("intent_created", "Intent Created"),
                            ("pending_confirmation", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("overridden", "Overridden"),
                            ("expired", "Expired"),
                        ],
                        default="intent_created",
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_reference", models.CharField(blank=True, max_length=150)),
                ("payment_proof", models.FileField(blank=True, null=True, upload_to="listing_payments/proofs/")),
                ("landlord_note", models.TextField(blank=True)),
                ("admin_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_listing_payment_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_payment_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="payments.listingplan",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_intents",
                        to="properties.property",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.RunPython(seed_listing_plans, migrations.RunPython.noop),
    ]
