# Generated by Django 6.0.2 on 2026-02-26 18:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_id_alter_payment_property_and_more'),
        ('properties', '0008_alter_property_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpaymentintent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listingpaymentintent',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='listingpaymentintent',
            name='landlord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_payment_intents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listingpaymentintent',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_intents', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='listingplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listingpaymentintent',
            index=models.Index(fields=['status'], name='payments_li_status_7698cd_idx'),
        ),
        migrations.AddIndex(
            model_name='listingpaymentintent',
            index=models.Index(fields=['landlord'], name='payments_li_landlor_b532e6_idx'),
        ),
        migrations.AddIndex(
            model_name='listingpaymentintent',
            index=models.Index(fields=['property'], name='payments_li_propert_7d98a8_idx'),
        ),
        migrations.AddIndex(
            model_name='listingpaymentintent',
            index=models.Index(fields=['expires_at'], name='payments_li_expires_c2d74f_idx'),
        ),
        migrations.AddIndex(
            model_name='listingpaymentintent',
            index=models.Index(fields=['status', 'expires_at'], name='payments_li_status_901864_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant'], name='payments_pa_tenant__f6b2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['property'], name='payments_pa_propert_ac6f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference'], name='payments_pa_referen_75358f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
    ]
