# Generated by Django 6.0.2 on 2026-02-27

import uuid
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0004_lease_updated_at_alter_lease_landlord_and_more"),
        ("payments", "0004_listingpaymentintent_updated_at_payment_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentInvoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("month", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ("due_date", models.DateField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("paid", "Paid"), ("overdue", "Overdue")], default="pending", max_length=20)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lease",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rent_invoices", to="leases.lease"),
                ),
            ],
            options={
                "ordering": ["-month", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="rentinvoice",
            constraint=models.UniqueConstraint(fields=("lease", "month"), name="uniq_invoice_per_lease_month"),
        ),
        migrations.AddIndex(
            model_name="rentinvoice",
            index=models.Index(fields=["status"], name="payments_ren_status_e4e2e5_idx"),
        ),
        migrations.AddIndex(
            model_name="rentinvoice",
            index=models.Index(fields=["lease"], name="payments_ren_lease_i_f02665_idx"),
        ),
        migrations.AddIndex(
            model_name="rentinvoice",
            index=models.Index(fields=["month"], name="payments_ren_month_0e2f0f_idx"),
        ),
        migrations.AddIndex(
            model_name="rentinvoice",
            index=models.Index(fields=["status", "due_date"], name="payments_ren_status_220c64_idx"),
        ),
    ]
