# Generated by Django 6.0.2 on 2026-02-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rentinvoice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rentinvoice',
            new_name='payments_re_status_64926c_idx',
            old_name='payments_ren_status_e4e2e5_idx',
        ),
        migrations.RenameIndex(
            model_name='rentinvoice',
            new_name='payments_re_lease_i_757a79_idx',
            old_name='payments_ren_lease_i_f02665_idx',
        ),
        migrations.RenameIndex(
            model_name='rentinvoice',
            new_name='payments_re_month_d77bee_idx',
            old_name='payments_ren_month_0e2f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='rentinvoice',
            new_name='payments_re_status_452e93_idx',
            old_name='payments_ren_status_220c64_idx',
        ),
    ]
