# Generated by Django 6.0.2 on 2026-02-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_updated_at_and_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_role_36d76d_idx',
            old_name='users_user_role_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_is_veri_cd7e9a_idx',
            old_name='users_user_verified_idx',
        ),
    ]
