# Generated by Django 6.0.2 on 2026-02-16 00:00

from django.db import migrations, models


def normalize_statuses(apps, schema_editor):
    RentalApplication = apps.get_model("applications", "RentalApplication")
    mappings = {
        "PENDING": "pending",
        "APPROVED": "approved",
        "REJECTED": "rejected",
        "VIEWING_SCHEDULED": "approved",
        "ACCEPTED": "approved",
        "LEASED": "approved",
        "ACTIVE": "approved",
        "CLOSED": "expired",
        "WITHDRAWN": "expired",
    }
    for old_status, new_status in mappings.items():
        RentalApplication.objects.filter(status=old_status).update(status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_application_workflow_constraints"),
    ]

    operations = [
        migrations.RunPython(normalize_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="rentalapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="rentalapplication",
            name="uniq_active_application_per_tenant_property",
        ),
        migrations.AddConstraint(
            model_name="rentalapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(status__in=["pending", "approved"]),
                fields=("tenant", "property"),
                name="uniq_active_application_per_tenant_property",
            ),
        ),
    ]
