# Generated by Django 6.0.2 on 2026-02-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_phase_b_application_workflow"),
        ("viewings", "0002_viewing_application"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalapplication",
            name="viewing",
        ),
    ]
