# Generated by Django 6.0.2 on 2026-02-26 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_rentalapplication_viewing'),
        ('properties', '0008_alter_property_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['status'], name='application_status_6b6860_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['tenant'], name='application_tenant__a69218_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['property'], name='application_propert_2cad2e_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['status', 'created_at'], name='application_status_87301d_idx'),
        ),
    ]
