# Generated by Django 6.0.2 on 2026-02-26 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='landlordverification',
            index=models.Index(fields=['status'], name='verificatio_status_3cb3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='landlordverification',
            index=models.Index(fields=['status', 'submitted_at'], name='verificatio_status_cf9525_idx'),
        ),
    ]
