# Generated by Django 6.0.2 on 2026-02-16 00:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_viewing_application(apps, schema_editor):
    RentalApplication = apps.get_model("applications", "RentalApplication")
    Viewing = apps.get_model("viewings", "Viewing")

    for application in RentalApplication.objects.exclude(viewing_id__isnull=True).iterator():
        Viewing.objects.filter(pk=application.viewing_id).update(application_id=application.id)


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_phase_b_application_workflow"),
        ("viewings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewing",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viewings",
                to="applications.rentalapplication",
            ),
        ),
        migrations.RunPython(backfill_viewing_application, migrations.RunPython.noop),
    ]
