# Generated by Django 6.0.2 on 2026-02-26 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_rentalapplication_updated_at_and_more'),
        ('properties', '0008_alter_property_options_and_more'),
        ('viewings', '0002_viewing_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewings', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewing_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='viewing',
            index=models.Index(fields=['status'], name='viewings_vi_status_39609f_idx'),
        ),
        migrations.AddIndex(
            model_name='viewing',
            index=models.Index(fields=['tenant'], name='viewings_vi_tenant__1dae0d_idx'),
        ),
        migrations.AddIndex(
            model_name='viewing',
            index=models.Index(fields=['property'], name='viewings_vi_propert_ddf0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='viewing',
            index=models.Index(fields=['scheduled_date'], name='viewings_vi_schedul_7053bc_idx'),
        ),
        migrations.AddIndex(
            model_name='viewing',
            index=models.Index(fields=['status', 'scheduled_date'], name='viewings_vi_status_155504_idx'),
        ),
        migrations.AddConstraint(
            model_name='viewing',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('tenant', 'property'), name='uniq_active_viewing_per_tenant_property'),
        ),
    ]
