# Generated by Django 6.0.2 on 2026-02-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
