# Generated by Django 6.0.2 on 2026-02-18 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_phase6_listing_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='admin_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='priority_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='propertyreviewlog',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('submitted', 'Submitted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyreviewlog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_review_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
