# Generated by Django 6.0.2 on 2026-02-26 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_updated_at_and_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__status_6427a0_idx',
            old_name='prop_status_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__verific_060ad3_idx',
            old_name='prop_verify_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__listing_e9734f_idx',
            old_name='prop_listing_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__locatio_2b40b0_idx',
            old_name='prop_location_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__price_32e7c2_idx',
            old_name='prop_price_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__priorit_e27492_idx',
            old_name='prop_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__status_5e103a_idx',
            old_name='prop_pubflow_idx',
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
