# Generated by Django 6.0.2 on 2026-02-27

import uuid
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0006_rentalapplication_updated_at_and_more"),
        ("properties", "0008_alter_property_options_and_more"),
        ("viewings", "0003_viewing_updated_at_alter_viewing_property_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalOffer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ("security_deposit", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("landlord_note", models.TextField(blank=True)),
                ("tenant_note", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("sent", "Sent"), ("accepted", "Accepted"), ("rejected", "Rejected"), ("withdrawn", "Withdrawn"), ("expired", "Expired")], default="sent", max_length=20)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("application", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="offer", to="applications.rentalapplication")),
                ("landlord", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sent_rental_offers", to=settings.AUTH_USER_MODEL)),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rental_offers", to="properties.property")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="received_rental_offers", to=settings.AUTH_USER_MODEL)),
                ("viewing", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="offers", to="viewings.viewing")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="rentaloffer",
            index=models.Index(fields=["status"], name="offers_rent_status_4f3af5_idx"),
        ),
        migrations.AddIndex(
            model_name="rentaloffer",
            index=models.Index(fields=["tenant"], name="offers_rent_tenant__067671_idx"),
        ),
        migrations.AddIndex(
            model_name="rentaloffer",
            index=models.Index(fields=["landlord"], name="offers_rent_landlor_50380f_idx"),
        ),
        migrations.AddIndex(
            model_name="rentaloffer",
            index=models.Index(fields=["property"], name="offers_rent_propert_cdc790_idx"),
        ),
        migrations.AddIndex(
            model_name="rentaloffer",
            index=models.Index(fields=["status", "created_at"], name="offers_rent_status_1c1885_idx"),
        ),
    ]

