# Generated by Django 6.0.2 on 2026-02-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rentaloffer',
            new_name='offers_rent_status_2f8a66_idx',
            old_name='offers_rent_status_4f3af5_idx',
        ),
        migrations.RenameIndex(
            model_name='rentaloffer',
            new_name='offers_rent_tenant__42c7a1_idx',
            old_name='offers_rent_tenant__067671_idx',
        ),
        migrations.RenameIndex(
            model_name='rentaloffer',
            new_name='offers_rent_landlor_085317_idx',
            old_name='offers_rent_landlor_50380f_idx',
        ),
        migrations.RenameIndex(
            model_name='rentaloffer',
            new_name='offers_rent_propert_bbbc98_idx',
            old_name='offers_rent_propert_cdc790_idx',
        ),
        migrations.RenameIndex(
            model_name='rentaloffer',
            new_name='offers_rent_status_8135bf_idx',
            old_name='offers_rent_status_1c1885_idx',
        ),
    ]
