# Generated by Django 6.0.2 on 2026-02-26 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_options_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertyreport',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyreport',
            name='reason',
            field=models.CharField(choices=[('fake_listing', 'Fake or fraudulent listing'), ('wrong_price', 'Incorrect pricing information'), ('inappropriate', 'Inappropriate content'), ('already_rented', 'Property already rented'), ('scam', 'Suspected scam'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyreport',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='blocked_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='blocker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propertyreport',
            index=models.Index(fields=['status'], name='reports_pro_status_706bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreport',
            index=models.Index(fields=['reporter'], name='reports_pro_reporte_ad3ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreport',
            index=models.Index(fields=['property'], name='reports_pro_propert_bcb19a_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreport',
            index=models.Index(fields=['status', 'created_at'], name='reports_pro_status_e1fe28_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyreport',
            index=models.Index(fields=['reviewed_by'], name='reports_pro_reviewe_9cea0d_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocker'], name='reports_use_blocker_2a647f_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocked_user'], name='reports_use_blocked_6da809_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['is_active'], name='reports_use_is_acti_d7fcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocker', 'blocked_user', 'is_active'], name='reports_use_blocker_ed9138_idx'),
        ),
    ]
