# Generated by Django 6.0.2 on 2026-02-26 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_rentalapplication_updated_at_and_more'),
        ('leases', '0003_lease_workflow_application_link'),
        ('properties', '0008_alter_property_options_and_more'),
        ('viewings', '0003_viewing_updated_at_alter_viewing_property_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landlord_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lease',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='lease',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lease',
            name='viewing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='viewings.viewing'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status'], name='leases_leas_status_d62744_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['tenant'], name='leases_leas_tenant__490bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['landlord'], name='leases_leas_landlor_c510f1_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['property'], name='leases_leas_propert_f07d89_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['start_date', 'end_date'], name='leases_leas_start_d_b1d1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status', 'end_date'], name='leases_leas_status_8d05bf_idx'),
        ),
    ]
