# Generated by Django 6.0.2 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0004_lease_updated_at_alter_lease_landlord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="landlord_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lease",
            name="tenant_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

